platform :ios, '11.0'

inhibit_all_warnings!

target 'Template' do
  
  pod 'AFNetworking', '~> 4.0.1'
  pod 'FMDB', '~> 2.7.5'
  pod 'Masonry', '~> 1.1.0'
  pod 'YYModel', '~> 1.0.4'
  pod 'YYCache', '~> 1.0.4'
  pod 'SDWebImage', '~> 5.12.5'
  pod 'VIMediaCache', '~> 0.4'
  pod 'MJRefresh', '~> 3.6.1'
  pod 'IQKeyboardManager', '~> 6.5.6'
  pod 'lottie-ios', '~> 3.3.0'
  pod 'TTTAttributedLabel', '~> 2.0.0'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 11.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
